controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    full_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    full_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    contact_pad_effort_controller:
      type: effort_controllers/JointGroupEffortController

full_arm_controller:
  ros__parameters:
    joints: [joint1_to_base, joint2_to_joint1, joint3_to_joint2, joint4_to_joint3, joint5_to_joint4, joint6_to_joint5]
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    allow_partial_joints_goal: false
    open_loop_control: true
    interpolation_method: splines

full_gripper_controller:
  ros__parameters:
    joints: [gripper_controller, gripper_base_to_gripper_left2, gripper_left3_to_gripper_left1, gripper_base_to_gripper_right3, gripper_base_to_gripper_right2, gripper_right3_to_gripper_right1]
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    allow_partial_joints_goal: false
    open_loop_control: true
    interpolation_method: splines

contact_pad_effort_controller:
  ros__parameters:
    joints: [left_contact_pad_joint, right_contact_pad_joint]
    interface_name: effort
